services:
  meu-bolso:
    container_name: meu-bolso
    build:
      context: .
      args:
        VITE_POCKETBASE_URL: "${VITE_POCKETBASE_URL}"
    ports:
      - "3080:3000"
    restart: unless-stopped
