/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as TransacoesRouteImport } from './routes/transacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planejamento': typeof PlanejamentoRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planejamento': typeof PlanejamentoRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planejamento': typeof PlanejamentoRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/planejamento' | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planejamento' | '/transacoes'
  id: '__root__' | '/' | '/planejamento' | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
